[server]
headless = true
port = 8501

[theme]
base = "dark"
primaryColor = "#64FFDA"
backgroundColor = "#0A1628"
secondaryBackgroundColor = "#112240"
textColor = "#CCD6F6"
font = "sans serif"

[browser]
gatherUsageStats = false
